### ISSUE TITLE
iPhone4 (and iPhone5) in landscape is not correctly recognized in devtools emulator

### ISSUE THREAD

**Issue by filipgolonka** [paranoida/sass-mediaqueries#29]
https://www.dropbox.com/s/i6wyfyxdnhew1gm/Screenshot%202015-01-21%2015.53.15.png?dl=0

Same issue with iPhone5 in landscape:
https://www.dropbox.com/s/odcyhulygm9jgxp/Screenshot%202015-01-21%2015.54.13.png?dl=0

Is it working under devtools emulator? I can't test it under real device (I have iPhone 6).

Solution is to change $deviceAspectRatio in proper mixin when device is in landscape mode.

**Comment by paranoida** [comment]
As far as I know the problem is somewhere in devtools. If you iOS emulator (xcode) you will see that everything works there (see below). Also, I always recommend using `max-screen` because you can target many devices at the same time. 

![screen shot 2015-01-21 at 20 58 25](https://cloud.githubusercontent.com/assets/130297/5843935/8c845dfe-a1b0-11e4-9fb1-568ea7d53b53.png)
![screen shot 2015-01-21 at 20 59 00](https://cloud.githubusercontent.com/assets/130297/5843936/8c862df0-a1b0-11e4-9bcc-80106dbbd7a9.png)
![screen shot 2015-01-21 at 20 59 34](https://cloud.githubusercontent.com/assets/130297/5843938/8c8c769c-a1b0-11e4-8fdc-ab0f5fcc7385.png)
![screen shot 2015-01-21 at 20 59 53](https://cloud.githubusercontent.com/assets/130297/5843937/8c86b324-a1b0-11e4-96e7-b0b785a62c0e.png)

**Comment by filipgolonka** [comment]
Thanks for the response!
